module Routes.AboutYou exposing (..)

import Html exposing (..)
import Html.Attributes exposing (..)
import Types exposing (..)
import Components.Help exposing (..)


aboutYou : Model -> Html Msg
aboutYou model =
    div [ class "pa1" ]
        [ div [ class "pa3 mt3 mb1 dark-gray b f4 flex justify-between" ] [ text "Can we 'quote' you?", help model 8 ]
        , div [ class "flex flex-wrap" ]
            [ input [ id "Yes", name "quote", type_ "radio", value "Yes", class "dn" ]
                []
            , label [ for "Yes", class "bg-white pa3 pointer ba b--mid-gray mw4 br1 ma2" ]
                [ text "Yes" ]
            , input [ id "No", name "quote", type_ "radio", value "No", class "dn" ]
                []
            , label [ for "No", class "bg-white pa3 pointer ba bb b--mid-gray mw4 br1 ma2" ]
                [ text "No" ]
            ]
        , div [ class "pa3 mt3 mb1 dark-gray b f4" ] [ text "What is your age Group?" ]
        , div [ class "flex flex-wrap" ]
            [ input [ id "under16", name "age", type_ "radio", value "under16", class "dn" ]
                []
            , label [ for "under16", class "bg-white pa3 pointer ba b--mid-gray mw4 br1 ma2" ]
                [ text "Under 16" ]
            , input [ id "16-17", name "age", type_ "radio", value "16-17", class "dn" ]
                []
            , label [ for "16-17", class "bg-white pa3 pointer ba bb b--mid-gray mw4 br1 ma2" ]
                [ text "16-17" ]
            , input [ id "18-24", name "age", type_ "radio", value "18-24", class "dn" ]
                []
            , label [ for "18-24", class "bg-white pa3 pointer ba bb b--mid-gray mw4 br1 ma2" ]
                [ text "18-24" ]
            , input [ id "25-34", name "age", type_ "radio", value "25-34", class "dn" ]
                []
            , label [ for "25-34", class "bg-white pa3 pointer ba bb b--mid-gray mw4 br1 ma2" ]
                [ text "25-34" ]
            , input [ id "35-44", name "age", type_ "radio", value "35-44", class "dn" ]
                []
            , label [ for "35-44", class "bg-white pa3 pointer ba bb b--mid-gray mw4 br1 ma2" ]
                [ text "35-44" ]
            , input [ id "45-54", name "age", type_ "radio", value "45-54", class "dn" ]
                []
            , label [ for "45-54", class "bg-white pa3 pointer ba bb b--mid-gray mw4 br1 ma2" ]
                [ text "45-54" ]
            , input [ id "55-64", name "age", type_ "radio", value "55-64", class "dn" ]
                []
            , label [ for "55-64", class "bg-white pa3 pointer ba bb b--mid-gray mw4 br1 ma2" ]
                [ text "55-64" ]
            , input [ id "65+", name "age", type_ "radio", value "65+", class "dn" ]
                []
            , label [ for "65+", class "bg-white pa3 pointer ba bb b--mid-gray mw4 br1 ma2" ]
                [ text "65+" ]
            , input [ id "Prefer not to say", name "age", type_ "radio", value "Prefer not to say", class "dn" ]
                []
            , label [ for "Prefer not to say", class "bg-white pa3 pointer ba bb b--mid-gray mw4 br1 ma2" ]
                [ text "Prefer not to say" ]
            ]
        , div [ class "pa3 mt3 mb1 dark-gray b f4" ] [ text "Do you consider yourself to have a disability?" ]
        , div [ class "flex flex-wrap " ]
            [ input [ id "Yes", name "disability", type_ "radio", value "Yes", class "dn" ]
                []
            , label [ for "Yes", class "bg-white pa3 pointer ba b--mid-gray mw4 br1 ma2" ]
                [ text "Yes" ]
            , input [ id "No", name "disability", type_ "radio", value "No", class "dn" ]
                []
            , label [ for "No", class "bg-white pa3 pointer ba bb b--mid-gray mw4 br1 ma2" ]
                [ text "No" ]
            , input [ id "disability not say", name "disability", type_ "radio", value "Prefer not to say", class "dn" ]
                []
            , label [ for "disability not say", class "bg-white pa3 pointer ba bb b--mid-gray mw4 br1 ma2" ]
                [ text "Prefer not to say" ]
            ]
        , div [ class "pa3 mt3 mb1 dark-gray b f4" ] [ text "If yes, please select all that apply, or skip if preferred" ]
        , div [ class "flex flex-wrap" ]
            [ input [ id "blindness", name "whatDisability", type_ "checkbox", value "blindness", class "dn" ]
                []
            , label [ for "blindness", class "bg-white pa3 pointer ba bb b--mid-gray mw4 br1 ma2" ]
                [ text "Blindness" ]
            , input [ id "visualImpairment", name "whatDisability", type_ "checkbox", value "visualImpairment", class "dn" ]
                []
            , label [ for "visualImpairment", class "bg-white pa3 pointer ba bb b--mid-gray mw4 br1 ma2" ]
                [ text "Visual impairment" ]
            , input [ id "deafness", name "whatDisability", type_ "checkbox", value "deafness", class "dn" ]
                []
            , label [ for "deafness", class "bg-white pa3 pointer ba bb b--mid-gray mw4 br1 ma2" ]
                [ text "Deafness" ]
            , input
                [ id "hearingImpairment", name "whatDisability", type_ "checkbox", value "hearingImpairment", class "dn" ]
                []
            , label [ for "hearingImpairment", class "bg-white pa3 pointer ba bb b--mid-gray mw4 br1 ma2" ]
                [ text "Hearing Impairment" ]
            , input
                [ id "learning", name "whatDisability", type_ "checkbox", value "learning", class "dn" ]
                []
            , label [ for "learning", class "bg-white pa3 pointer ba bb b--mid-gray mw4 br1 ma2" ]
                [ text "Learning Difficulty" ]
            , input
                [ id "mentalHealth", name "whatDisability", type_ "checkbox", value "mentalHealth", class "dn" ]
                []
            , label [ for "mentalHealth", class "bg-white pa3 pointer ba bb b--mid-gray mw4 br1 ma2" ]
                [ text "Mental ill-health" ]
            , input
                [ id "mobility", name "whatDisability", type_ "checkbox", value "mobility", class "dn" ]
                []
            , label [ for "mobility", class "bg-white pa3 pointer ba bb b--mid-gray mw4 br1 ma2" ]
                [ text "Restricted Mobility" ]
            ]
        , div [ class "pa2 ma2" ]
            [ text "Other: "
            , input [ name "Other", placeholder "Please write here", type_ "text", class "ba b--mid-gray f5 ml2 pa1" ]
                []
            ]
        , div [ class "pa3 mt3 mb1 dark-gray b f4" ] [ text "Ethnic Background" ]
        , div [ class "ml3" ]
            [ text "Please select from list: "
            , select [ class "f5 ba  b--mid-gray pa1 ml2" ]
                [ option [ value "Please select" ]
                    [ text "Please select" ]
                , option [ value "Asian - Bangladeshi" ]
                    [ text "Asian - Bangladeshi" ]
                , option [ value "Asian - British" ]
                    [ text "Asian - British" ]
                , option [ value "Asian - Indian" ]
                    [ text "Asian - Indian" ]
                , option [ value "Asian - Pakistani" ]
                    [ text "Asian - Pakistani" ]
                , option [ value "Black - African" ]
                    [ text "Black - African" ]
                , option [ value "Black - British" ]
                    [ text "Black - British" ]
                , option [ value "Black- Caribbean" ]
                    [ text "Black- Caribbean" ]
                , option [ value "Chinese" ]
                    [ text "Chinese" ]
                , option [ value "Latin American" ]
                    [ text "Latin American" ]
                , option [ value "Middle Eastern" ]
                    [ text "Middle Eastern" ]
                , option [ value "Mixed Ethnicity" ]
                    [ text "Mixed Ethnicity" ]
                , option [ value "White - British" ]
                    [ text "White - British" ]
                , option [ value "White - Irish" ]
                    [ text "White - Irish" ]
                , option [ value "White - European" ]
                    [ text "White - European" ]
                , option [ value "Prefer not to say" ]
                    [ text "Prefer not to say" ]
                ]
            , div [ class "mt3" ]
                [ text "Other: "
                , input [ name "Other", placeholder "Please write here", type_ "text", class "ba b--mid-gray f5 ml2 pa1" ]
                    []
                ]
            ]
        , div [ class "pa3 mt3 mb1 dark-gray b f4" ] [ text "Religion & Belief" ]
        , div [ class "ml3" ]
            [ text "Please select from list: "
            , select [ class "f5 ba  b--mid-gray pa1 ml2" ]
                [ option [ value "Please select" ]
                    [ text "Please select" ]
                , option [ value "Agnostic" ]
                    [ text "Agnostic" ]
                , option [ value "Atheist" ]
                    [ text "Atheist" ]
                , option [ value "Baha'i" ]
                    [ text "Baha'i" ]
                , option [ value "Buddhist" ]
                    [ text "Buddhist" ]
                , option [ value "Christian" ]
                    [ text "Christian" ]
                , option [ value "Hindu" ]
                    [ text "Hindu" ]
                , option [ value "Humanist" ]
                    [ text "Humanist" ]
                , option [ value "Jain" ]
                    [ text "Jain" ]
                , option [ value "Jewish" ]
                    [ text "Jewish" ]
                , option [ value "Muslim" ]
                    [ text "Muslim" ]
                , option [ value "Rastafarian" ]
                    [ text "Rastafarian" ]
                , option [ value "Sikh" ]
                    [ text "Sikh" ]
                , option [ value "Zoroastrian" ]
                    [ text "Zoroastrian" ]
                , option [ value "None" ]
                    [ text "None" ]
                , option [ value "Prefer not to say" ]
                    [ text "Prefer not to say" ]
                ]
            , div [ class "mt3" ]
                [ text "Other: "
                , input [ name "Other", placeholder "Please write here", type_ "text", class "ba b--mid-gray f5 ml2 pa1" ]
                    []
                ]
            ]
        , div [ class "pa3 mt3 mb1 dark-gray b f4" ] [ text "Sexuality" ]
        , div [ class "ml3" ]
            [ text "Please select from list: "
            , select [ class "f5 ba  b--mid-gray pa1 ml2" ]
                [ option [ value "Please select" ]
                    [ text "Please select" ]
                , option [ value "Bisexual" ]
                    [ text "Bisexual" ]
                , option [ value "Gay" ]
                    [ text "Gay" ]
                , option [ value "Lesbian" ]
                    [ text "Lesbian" ]
                , option [ value "Hetrosexual" ]
                    [ text "Hetrosexual" ]
                , option [ value "None" ]
                    [ text "None" ]
                , option [ value "Prefer not to say" ]
                    [ text "Prefer not to say" ]
                ]
            , div [ class "mt3" ]
                [ text "Other: "
                , input [ name "Other", placeholder "Please write here", type_ "text", class "ba b--mid-gray f5 ml2 pa1" ]
                    []
                ]
            ]
        , div [ class "pa3 mt3 mb1 dark-gray b f4" ] [ text "Do you live in:" ]
        , div [ class "flex flex-wrap " ]
            [ input [ id "A City", name "live", type_ "radio", value "A City", class "dn" ]
                []
            , label [ for "A City", class "bg-white pa3 pointer ba b--mid-gray mw4 br1 ma2" ]
                [ text "A City" ]
            , input [ id "A Town", name "live", type_ "radio", value "A Town", class "dn" ]
                []
            , label [ for "A Town", class "bg-white pa3 pointer ba bb b--mid-gray mw4 br1 ma2" ]
                [ text "A Town" ]
            , input [ id "A Village", name "live", type_ "radio", value "A Village", class "dn" ]
                []
            , label [ for "A Village", class "bg-white pa3 pointer ba bb b--mid-gray mw4 br1 ma2" ]
                [ text "A Village" ]
            , input [ id "Countryside", name "live", type_ "radio", value "Countryside", class "dn" ]
                []
            , label [ for "Countryside", class "bg-white pa3 pointer ba bb b--mid-gray mw4 br1 ma2" ]
                [ text "Countryside" ]
            ]
        , div [ class "pa3 mt3 mb1 dark-gray b f4" ] [ text "Where do you live?:" ]
        , div [ class "flex flex-wrap " ]
            [ input [ id "Scotland", name "location", type_ "radio", value "Scotland", class "dn" ]
                []
            , label [ for "Scotland", class "bg-white pa3 pointer ba b--mid-gray mw4 br1 ma2" ]
                [ text "Scotland" ]
            , input [ id "Wales", name "location", type_ "radio", value "Wales", class "dn" ]
                []
            , label [ for "Wales", class "bg-white pa3 pointer ba bb b--mid-gray mw4 br1 ma2" ]
                [ text "Wales" ]
            , input [ id "North East England", name "location", type_ "radio", value "North East England", class "dn" ]
                []
            , label [ for "North East England", class "bg-white pa3 pointer ba bb b--mid-gray mw4 br1 ma2" ]
                [ text "North East England" ]
            , input [ id "North West England", name "location", type_ "radio", value "North West England", class "dn" ]
                []
            , label [ for "North West England", class "bg-white pa3 pointer ba bb b--mid-gray mw4 br1 ma2" ]
                [ text "North West England" ]
            , input [ id "South East England", name "location", type_ "radio", value "South East England", class "dn" ]
                []
            , label [ for "South East England", class "bg-white pa3 pointer ba bb b--mid-gray mw4 br1 ma2" ]
                [ text "South East England" ]
            , input [ id "South West England", name "location", type_ "radio", value "South West England", class "dn" ]
                []
            , label [ for "South West England", class "bg-white pa3 pointer ba bb b--mid-gray mw4 br1 ma2" ]
                [ text "South West England" ]
            , input [ id "Yorkshire and Humber", name "location", type_ "radio", value "Yorkshire and Humber", class "dn" ]
                []
            , label [ for "Yorkshire and Humber", class "bg-white pa3 pointer ba bb b--mid-gray mw4 br1 ma2" ]
                [ text "Yorkshire and Humber" ]
            , input [ id "East Midlands", name "location", type_ "radio", value "East Midlands", class "dn" ]
                []
            , label [ for "East Midlands", class "bg-white pa3 pointer ba bb b--mid-gray mw4 br1 ma2" ]
                [ text "East Midlands" ]
            , input [ id "West Midlands", name "location", type_ "radio", value "West Midlands", class "dn" ]
                []
            , label [ for "West Midlands", class "bg-white pa3 pointer ba bb b--mid-gray mw4 br1 ma2" ]
                [ text "West Midlands" ]
            , input [ id "East Anglia", name "location", type_ "radio", value "East Anglia", class "dn" ]
                []
            , label [ for "East Anglia", class "bg-white pa3 pointer ba bb b--mid-gray mw4 br1 ma2" ]
                [ text "East Anglia" ]
            , input [ id "London", name "location", type_ "radio", value "London", class "dn" ]
                []
            , label [ for "London", class "bg-white pa3 pointer ba bb b--mid-gray mw4 br1 ma2" ]
                [ text "London" ]
            , input [ id "Not Sure", name "location", type_ "radio", value "Not Sure", class "dn" ]
                []
            , label [ for "Not Sure", class "bg-white pa3 pointer ba bb b--mid-gray mw4 br1 ma2" ]
                [ text "Not Sure" ]
            , div [ class "mt3 ml3" ]
                [ text "Other: "
                , input [ name "Other", placeholder "Please write here", type_ "text", class "ba b--mid-gray f5 ml2 pa1" ]
                    []
                ]
            ]
        , a [ class "orange-button", href "#thanks" ] [ text "next" ]
        ]
