module Routes.Journey exposing (..)

import Html exposing (..)
import Html.Attributes exposing (..)
import Types exposing (..)
import Components.Help exposing (..)


journey : Model -> Html Msg
journey model =
    div [ class "mh2" ]
        [ div [ class "pa2 mt3 mb1 dark-gray b f4 flex" ] [ text "Who did you go to for help?", help model 1 ]
        , div [ class "flex flex-wrap br2 pa1" ]
            [ input [ class "dn", id "none", name "who", type_ "checkbox", value "none" ]
                []
            , label [ class "bg-white flex items-center ph3 pv1 pointer ba bb b--mid-gray mw4 br1 ma1 tc", for "none" ]
                [ text "No one" ]
            , input [ class "dn", id "family", name "who", type_ "checkbox", value "family" ]
                []
            , label [ class "bg-white flex items-center ph3 pv1 pointer ba bb b--mid-gray mw4 br1 ma1 tc", for "family" ]
                [ text "Family" ]
            , input [ class "dn", id "friends", name "who", type_ "checkbox", value "friends" ]
                []
            , label [ class "bg-white flex items-center ph3 pv1 pointer ba bb b--mid-gray mw4 br1 ma1 tc", for "friends" ]
                [ text "Friends" ]
            , input [ class "dn", id "neighbours", name "who", type_ "checkbox", value "neighbours" ]
                []
            , label [ class "bg-white flex items-center ph3 pv1 pointer ba bb b--mid-gray mw4 br1 ma1 tc", for "neighbours" ]
                [ text "Neighbours" ]
            , input [ class "dn", id "police", name "who", type_ "checkbox", value "police" ]
                []
            , label [ class "bg-white flex items-center ph3 pv1 pointer ba bb b--mid-gray mw4 br1 ma1 tc", for "police" ]
                [ text "Police" ]
            , input [ class "dn", id "social", name "who", type_ "checkbox", value "social" ]
                []
            , label [ class "bg-white flex items-center ph3 pv1 pointer ba bb b--mid-gray mw4 br1 ma1 tc", for "social" ]
                [ text "Social Services" ]
            , input [ class "dn", id "local", name "who", type_ "checkbox", value "local" ]
                []
            , label [ class "bg-white flex items-center ph3 pv1 pointer ba bb b--mid-gray mw4 br1 ma1 tc", for "local" ]
                [ text "Local Authority" ]
            , input [ class "dn", id "nhs", name "who", type_ "checkbox", value "nhs" ]
                []
            , label [ class "bg-white flex items-center ph3 pv1 pointer ba bb b--mid-gray mw4 br1 ma1 tc", for "nhs" ]
                [ text "NHS Services" ]
            , input [ class "dn", id "specialist", name "who", type_ "checkbox", value "specialist" ]
                []
            , label [ class "bg-white flex items-center ph3 pv1 pointer ba bb b--mid-gray mw4 br1 ma1 tc", for "specialist" ]
                [ text "Specialist Services" ]
            , input [ class "dn", id "legal", name "who", type_ "checkbox", value "legal" ]
                []
            , label [ class "bg-white flex items-center ph3 pv1 pointer ba bb b--mid-gray mw4 br1 ma1 tc", for "legal" ]
                [ text "Legal Services" ]
            ]
        , div [ class "mh1" ]
            [ label [ class "dib bg-white items-center pv1 pointer mw4 br1 ma1 tc", for "other" ]
                [ text "Other:" ]
            , textarea [ class "v-mid mh1 bg-light-gray b b--mid-gray vh-10 dib", placeholder "Please tell us here" ]
                []
            ]
        , div [ class "pa2 mt3 mb1 dark-gray b f4 flex" ] [ text "Who did you find helpful and why?", help model 2 ]
        , div [ class "flex justify-center mt3 mb3 vh-20" ]
            [ textarea [ class "bg-light-gray ba b--mid-gray w-90", placeholder "Who did you find helpful and why?" ]
                []
            ]
        , div [ class "pa2 mt3 mb1 dark-gray b f4 flex" ] [ text "Who did you find unhelpful and why?", help model 3 ]
        , div [ class "flex justify-center mt3 mb3 vh-20" ]
            [ textarea [ class "bg-light-gray ba b--mid-gray w-90", placeholder "Who did you find unhelpful and why?" ]
                []
            ]
        , div [ class "pa2 mt3 mb1 dark-gray b f4 flex" ] [ text "What other help would you have liked?", help model 4 ]
        , div [ class "flex justify-center mt3 mb3 vh-20" ]
            [ textarea [ class "bg-light-gray ba b--mid-gray w-90", placeholder "What other help would you have liked?" ]
                []
            ]
        , div
            [ class "ph2 pv1 mt3 mb1 dark-gray b f4 flex" ]
            [ text "A bit more about your experience", help model 5 ]
        , div [ class "flex flex-wrap bg-light-gray br2 pa1 mh2" ]
            [ input [ class "dn", id "prostitution", name "tags", type_ "checkbox", value "prostitution" ]
                []
            , label [ class "bg-white flex items-center ph3 pv1 pointer ba bb b--mid-gray mw4 br1 ma1 tc", for "prostitution" ]
                [ text "Prostitution" ]
            , br []
                []
            , input [ class "dn", id "alcohol", name "tags", type_ "checkbox", value "alcohol" ]
                []
            , label [ class "bg-white flex items-center ph3 pv1 pointer ba bb b--mid-gray mw4 br1 ma1 tc", for "alcohol" ]
                [ text "Alcohol abuse" ]
            , br []
                []
            , input [ class "dn", id "Poverty", name "tags", type_ "checkbox", value "Poverty" ]
                []
            , label [ class "bg-white flex items-center ph3 pv1 pointer ba bb b--mid-gray mw4 br1 ma1 tc", for "Poverty" ]
                [ text "Poverty" ]
            , br []
                []
            , input [ class "dn", id "drugs", name "tags", type_ "checkbox", value "drugs" ]
                []
            , label [ class "bg-white flex items-center ph3 pv1 pointer ba bb b--mid-gray mw4 br1 ma1 tc", for "drugs" ]
                [ text "Drug Abuse" ]
            , input [ class "dn", id "child", name "tags", type_ "checkbox", value "child" ]
                []
            , label [ class "bg-white flex items-center ph3 pv1 pointer ba bb b--mid-gray mw4 br1 ma1 tc", for "child" ]
                [ text "Child removed" ]
            , input [ class "dn", id "homelessness", name "tags", type_ "checkbox", value "homelessness" ]
                []
            , label [ class "bg-white flex items-center ph3 pv1 pointer ba bb b--mid-gray mw4 br1 ma1 tc", for "homelessness" ]
                [ text "Homelessness" ]
            , input [ class "dn", id "childhoodtrauma", name "tags", type_ "checkbox", value "childhoodtrauma" ]
                []
            , label [ class "bg-white flex items-center ph3 pv1 pointer ba bb b--mid-gray mw4 br1 ma1 tc", for "childhoodtrauma" ]
                [ text "Childhood Trauma" ]
            , input [ class "dn", id "social", name "tags", type_ "checkbox", value "social" ]
                []
            , label [ class "bg-white flex items-center ph3 pv1 pointer ba bb b--mid-gray mw4 br1 ma1 tc", for "social" ]
                [ text "Adult Social Services" ]
            , input [ class "dn", id "mental", name "tags", type_ "checkbox", value "mental" ]
                []
            , label [ class "bg-white flex items-center ph3 pv1 pointer ba bb b--mid-gray mw4 br1 ma1 tc", for "mental" ]
                [ text "Mental Health" ]
            , input [ class "dn", id "criminaljustice", name "tags", type_ "checkbox", value "criminaljustice" ]
                []
            , label [ class "bg-white flex items-center ph3 pv1 pointer ba bb b--mid-gray mw4 br1 ma1 tc", for "criminaljustice" ]
                [ text "Involvement in criminal justice system" ]
            , input [ class "dn", id "carer", name "tags", type_ "checkbox", value "carer" ]
                []
            , label [ class "bg-white flex items-center ph3 pv1 pointer ba bb b--mid-gray mw4 br1 ma1 tc", for "carer" ]
                [ text "Carer" ]
            , input [ class "dn", id "pregnant", name "tags", type_ "checkbox", value "pregnant" ]
                []
            , label [ class "bg-white flex items-center ph3 pv1 pointer ba bb b--mid-gray mw4 br1 ma1 tc", for "pregnant" ]
                [ text "Pregnant while facing abuse" ]
            , input [ class "dn", id "parent", name "tags", type_ "checkbox", value "parent" ]
                []
            , label [ class "bg-white flex items-center ph3 pv1 pointer ba bb b--mid-gray mw4 br1 ma1 tc", for "parent" ]
                [ text "Parent" ]
            ]
        , div [ class "pa3 mt3 mb1 dark-gray b f4 flex" ] [ text "Anything else you want to tell us?", help model 6 ]
        , div [ class "flex justify-center mt3 mb3 vh-20" ]
            [ textarea [ class "bg-light-gray ba b--mid-gray w-90", placeholder "Please write here" ]
                []
            ]
        , div
            [ class "ph3 pv1 mt3 mb1 dark-gray b f4" ]
            [ text "When did this experience happen to you?" ]
        , div [ class "flex flex-wrap br2 pa1" ]
            [ input [ class "dn", id "currently", name "when", type_ "checkbox", value "currently" ]
                []
            , label [ class "bg-white flex items-center ph3 pv1 pointer ba bb b--mid-gray mw4 br1 ma1 tc", for "currently" ]
                [ text "Currently" ]
            , input [ class "dn", id "underayear", name "when", type_ "checkbox", value "underayear" ]
                []
            , label [ class "bg-white flex items-center ph3 pv1 pointer ba bb b--mid-gray mw4 br1 ma1 tc", for "underayear" ]
                [ text "Under a year" ]
            , input [ class "dn", id "1or2years", name "when", type_ "checkbox", value "1or2years" ]
                []
            , label [ class "bg-white flex items-center ph3 pv1 pointer ba bb b--mid-gray mw4 br1 ma1 tc", for "1or2years" ]
                [ text "1-2 years ago" ]
            , input [ class "dn", id "2or5years", name "when", type_ "checkbox", value "2or5years" ]
                []
            , label [ class "bg-white flex items-center ph3 pv1 pointer ba bb b--mid-gray mw4 br1 ma1 tc", for "2or5years" ]
                [ text "2-5 years ago" ]
            , input [ class "dn", id "5or10years", name "when", type_ "checkbox", value "5or10years" ]
                []
            , label [ class "bg-white flex items-center ph3 pv1 pointer ba bb b--mid-gray mw4 br1 ma1 tc", for "5or10years" ]
                [ text "5-10 years ago" ]
            , input [ class "dn", id "10years", name "when", type_ "checkbox", value "10years" ]
                []
            , label [ class "bg-white flex items-center ph3 pv1 pointer ba bb b--mid-gray mw4 br1 ma1 tc", for "10years" ]
                [ text "10 years or more" ]
            , input [ class "dn", id "noanswer", name "when", type_ "checkbox", value "noanswer" ]
                []
            , label [ class "bg-white flex items-center ph3 pv1 pointer ba bb b--mid-gray mw4 br1 ma1 tc", for "noanswer" ]
                [ text "Prefer not to say" ]
            ]
        , a [ class "orange-button", href "#government" ] [ text "next" ]
        ]
