module Routes.Journey exposing (..)

import Html exposing (..)
import Html.Attributes exposing (..)
import Types exposing (..)


journey : Model -> Html Msg
journey model =
    div [ class "mh2" ]
        [ fieldset []
            [ legend []
                [ text "Please let us know what has affected you." ]
            , input [ id "prostitution", name "tags", type_ "checkbox", value "prostitution" ]
                []
            , label [ for "prostitution" ]
                [ text "Prostitution" ]
            , br []
                []
            , input [ id "alcohol", name "tags", type_ "checkbox", value "alcohol" ]
                []
            , label [ for "alcohol" ]
                [ text "Alcohol abuse" ]
            , br []
                []
            , input [ id "Poverty", name "tags", type_ "checkbox", value "Poverty" ]
                []
            , label [ for "Poverty" ]
                [ text "Poverty" ]
            , br []
                []
            , input [ id "drugs", name "tags", type_ "checkbox", value "drugs" ]
                []
            , label [ for "drugs" ]
                [ text "Drug Abuse" ]
            , input [ id "child", name "tags", type_ "checkbox", value "child" ]
                []
            , label [ for "child" ]
                [ text "Child removed" ]
            , input [ id "homelessness", name "tags", type_ "checkbox", value "homelessness" ]
                []
            , label [ for "homelessness" ]
                [ text "Homelessness" ]
            , input [ id "childhoodtrauma", name "tags", type_ "checkbox", value "childhoodtrauma" ]
                []
            , label [ for "childhoodtrauma" ]
                [ text "Childhood Trauma" ]
            , input [ id "social", name "tags", type_ "checkbox", value "social" ]
                []
            , label [ for "social" ]
                [ text "Adult Social Services" ]
            , input [ id "mental", name "tags", type_ "checkbox", value "mental" ]
                []
            , label [ for "mental" ]
                [ text "Mental Health" ]
            , input [ id "criminaljustice", name "tags", type_ "checkbox", value "criminaljustice" ]
                []
            , label [ for "criminaljustice" ]
                [ text "Involvement in criminal justice system" ]
            , input [ id "carer", name "tags", type_ "checkbox", value "carer" ]
                []
            , label [ for "carer" ]
                [ text "Carer" ]
            , input [ id "pregnant", name "tags", type_ "checkbox", value "pregnant" ]
                []
            , label [ for "pregnant" ]
                [ text "Pregnant while facing abuse" ]
            , input [ id "parent", name "tags", type_ "checkbox", value "parent" ]
                []
            , label [ for "parent" ]
                [ text "Parent" ]
            ]
        ]
